#! /usr/bin/python3

import plotext as plt
import sys
import os
from PIL import Image

pwd=os.getcwd()
relpath=sys.argv[1]
path=pwd+"/"+relpath

# Open the image to get its original dimensions
with Image.open(path) as img:
    original_width, original_height = img.size
    #print(original_width, original_height)
# Desired terminal height
terminal_height = 55

# Calculate the new width to maintain the aspect ratio
new_width = int(terminal_height*original_width/original_height*1.82)

plt.play_gif(path)
